on:
  workflow_dispatch

name: Build-Alpine

jobs:
  prebuild-node:
    name: Upload Node Prebuild
    runs-on: ubuntu-latest

    container:
      image: node:14-alpine
      
    steps:
      - uses: actions/checkout@v2
        with:
          repository: "JoshuaWise/better-sqlite3"
      - name: Install Make tools
        run: apk add --update --no-cache bash git openssh make cmake alpine-sdk
      - name: Install Python
        run: apk add --update --no-cache python3 && ln -sf python3 /usr/bin/python
      - run: python --version  
      - name: Install global packages
        run: npm i -g npe detect-libc
      - name: Change ABI version
        run: npe "devDependencies.node-abi" "2.18.0"
      - name: Install packages
        run: npm install && npm list || true
      - name: Change package name
        run: npe name "better-sqlite3-with-prebuilds" && npe repository.url "git+https://github.com/apify/better-sqlite3-with-prebuilds.git"
      - name: Show package.json
        run: cat package.json
      - name: Build release
        run: |
          detect-libc node ./node_modules/prebuild/bin.js -r electron -t 10.0.0 --include-regex 'better_sqlite3.node$' -u ${{ secrets.GITHUB_TOKEN }}
