on:
  workflow_dispatch

name: Publish

jobs:
  prebuild-node:
    name: Publish package to npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: "JoshuaWise/better-sqlite3"
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install
      - name: Change package name
        run: npm i npe -g && npe name "better-sqlite3-with-prebuilds" && npe repository.url "git+https://github.com/nrob81/better-sqlite3-with-prebuilds.git"
      - name: Download lzz
        run: curl -sSL https://github.com/driedfruit/lzz/releases/download/v2.8.2/lzz_2_8_2_linux64.zip > lzz.zip
      - name: Unzip lzz
        run: unzip lzz.zip
      - name: DEBUG ZIP
        run: ls -la
      - name: Move to lzz usr/bin
        run: sudo mv lzz /usr/local/bin && rm -rf lzz.zip
      - uses: JS-DevTools/npm-publish@v1
        continue-on-error: true # release might be already done and the prepublish fails on windows
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: "public"
          dry-run: false
